name: Windows

on: [push]

concurrency:
  group: ci-windows-msvc-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  iconv_version: 'v1.14.0+3'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x64 ]

    runs-on: windows-2025

    defaults:
      run:
        shell: cmd

    steps:

    - uses: actions/checkout@v7

    - name: Setup VC++ environment (VCVARSALL)
      run: for /f "usebackq tokens=*" %%i in (`vswhere -products * -latest -property installationPath`) do (echo VCVARSALL=%%i\VC\Auxiliary\Build\vcvarsall.bat) >> %GITHUB_ENV%

    - name: libiconv
      run: |
        IF NOT EXIST tmp MKDIR tmp
        CD tmp
        SET LIBICONV_NAME=libiconv-${{ env.iconv_version }}-windows-${{ matrix.arch }}
        curl -LO "https://github.com/koron/libiconv/releases/download/${{ env.iconv_version }}/%LIBICONV_NAME%.zip"
        unzip -o "%LIBICONV_NAME%.zip"
        REN "%LIBICONV_NAME%" local

    - name: build
      run: |
        call "%VCVARSALL%" ${{ matrix.arch }}
        nmake /NOLOGO /F Makefile.msvc DLL=1 MFLAGS="-MD -D_BIND_TO_CURRENT_VCLIBS_VERSION=1" PREFIX="${{ github.workspace }}\tmp\local"

    - name: install
      run: |
        call "%VCVARSALL%" ${{ matrix.arch }}
        nmake /NOLOGO /F Makefile.msvc DLL=1 MFLAGS="-MD -D_BIND_TO_CURRENT_VCLIBS_VERSION=1" PREFIX="${{ github.workspace }}\tmp\local2" install

    - name: archive artifacts
      uses: actions/upload-artifact@v7
      with:
        name: gettext-windows-${{ matrix.arch }}
        path: |
          tmp/local2

  dist:
    if: github.ref_type == 'tag'
    needs: [ build ]

    runs-on: windows-2025

    defaults:
      run:
        shell: cmd

    steps:

    - name: download artifacts
      uses: actions/download-artifact@v8
      with:
        name: gettext-windows-x64
        path: gettext-${{ github.ref_name }}-windows-x64

    - name: download artifacts
      uses: actions/download-artifact@v8
      with:
        name: gettext-windows-x86
        path: gettext-${{ github.ref_name }}-windows-x86

    - name: install zip command
      run:
         choco install zip

    - name: zip archive
      run: |
        SET GETTEXT_NAME=gettext-${{ github.ref_name }}-windows-x64
        zip -r9q "%GETTEXT_NAME%.zip" "%GETTEXT_NAME%"
        SET GETTEXT_NAME=gettext-${{ github.ref_name }}-windows-x86
        zip -r9q "%GETTEXT_NAME%.zip" "%GETTEXT_NAME%"

    - name: list zip
      run: DIR *.zip

    - name: release
      uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
        files: |
          *.zip
        fail_on_unmatched_files: true
        generate_release_notes: false
        append_body: true
